# HotwireBits Documentation Site

source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "puma"
gem "turbo-rails"
gem "stimulus-rails"
gem "view_component", "~> 3.0"
gem "hotwirebits", path: "../"

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end
